### ISSUE TITLE
server tsconfig.json

### ISSUE THREAD

**Issue by billbarni** [dbranco/aprendiendo_meanstack#1]
There is no tsconfig.json file in the server folder, that causes an error when trying to run it with npm. Am I doing something wrong or should I just create the file?
(Sorry about writing this in english, my spanish is very bad)

**Comment by dbranco** [comment]
Hey man I just abandoned this project and begin new one with Angular 4 in mind. Check the other repository, https://github.com/dbranco/learning_mean_stack if you go to the wiki it has more explanation about I have done, for now it is a little stop because I havent had patience and time to read about angular forms.
